New method of getting wrf_stats and plotting results

diff --git a/scripts/wrf_run_pbs_jobs b/scripts/wrf_run_pbs_jobs
--- a/scripts/wrf_run_pbs_jobs
+++ b/scripts/wrf_run_pbs_jobs
@@ -1,25 +1,27 @@
 #!/bin/sh
 
 help() {
-    echo ""
-    echo "Usage: ${0##*/} [-h] [-d DIR] [-t NUM] -w WRF1 WRF2 ... -n X Y Z ... -c CASE1 CASE2 ..."
-    echo "Creates and submits a series of PBS jobs scripts for all combinations of parameters"
-    echo ""
-    echo "OPTIONS:"
-    echo "    -w, --wrfs  WRF_DIR LIST     Directories of compiled WRF versions to use."
-    echo "    -n, --nodes NUM_NODES LIST   Number of nodes to use."
-    echo "    -c, --cases CASE_DIR LIST    Directories with cases to run, each containing a namelist.input, wrfbdy, and wrfinput or wrfrst."
-    echo "    -t, --trial NUM              A trial number to avoid overwriting a previous run with the same parameters. [default 1]"
-    echo "    -r, --rundir RUN_DIR         Directory to which to place run output. [default ~/work/run]"
-    echo "    -a, --walltime 'HH:MM:SS'    Walltime for all submitted jobs. [default 00:30:00]"
-    echo "    -e, --envvars ENV_VAR LIST   Environment variables to be set."
-    echo "    -h, --help                   This help"
-    echo ""
-    exit 0
+echo ""
+echo "Usage: ${0##*/} [-h] [-r DIR] [-a 'HH:MM:SS'] [-e VAR1 VAR2 ...] [-t N1 N2 ...]"
+echo "                               -w WRF1 WRF2 ... -c CASE1 CASE2 ... -n X Y Z ..."
+echo "Creates and submits a series of PBS jobs scripts for all combinations of parameters"
+echo ""
+echo "OPTIONS:"
+echo "    -w, --wrfs  WRF_DIR LIST     Directories of compiled WRF versions to use."
+echo "    -c, --cases CASE_DIR LIST    Directories with cases to run, each containing a"
+echo "                                    namelist.input, wrfbdy, and wrfinput or wrfrst."
+echo "    -n, --nodes NUM_NODES LIST   Number of nodes to use."
+echo "    -t, --trials NUM LIST        Run each combination for each trial number, avoids overwriting "
+echo "                                    previous runs with the same parameters. [default 1]"
+echo "    -r, --rundir RUN_DIR         Directory to which to place run output. [default ~/work/run]"
+echo "    -a, --walltime 'HH:MM:SS'    Walltime for all submitted jobs. [default 00:30:00]"
+echo "    -e, --envvars ENV_VAR LIST   Environment variables to be set."
+echo "    -h, --help                   This help"
+echo ""
+exit 0
 }
 
 reading_list=none
-TRIAL_NUM=1
 RUN_DIR=~/work/run
 WALL_TIME='00:30:00'
 
@@ -34,10 +36,8 @@ do
             reading_list=cases ;;
         -e|--envvars)
             reading_list=envvars ;;
-        -t|--trial)
-            reading_list=none
-            TRIAL_NUM=$2
-            shift ;;
+        -t|--trials)
+            reading_list=trials ;;
         -r|--rundir)
             reading_list=none
             RUN_DIR=$2
@@ -53,6 +53,7 @@ do
             elif [ "$reading_list" = nodes   ] ; then NODES+=($1)
             elif [ "$reading_list" = cases   ] ; then CASES+=("$1")
             elif [ "$reading_list" = envvars ] ; then ENVVARS+=("$1")
+            elif [ "$reading_list" = trials  ] ; then TRIALSS+=("$1")
             else
                 help
             fi
@@ -61,41 +62,51 @@ do
 	  shift
 done
 
-if [ ${#ENVVARS[@]} -eq 0 ]; then
+if [ -z $WRFs ]; then
+    echo "at least one WRF_DIR must be specified"; help
+fi
+if [ -z $NODES ]; then
+    echo "at least one NUM_NODES must be specified"; help
+fi
+if [ -z $CASES ]; then
+    echo "at least one CASE_DIR must be specified"; help
+fi
+if [ ${#ENVVARS[@]} -gt 0 ]; then
    ENV_STR=$(printf "export %s\n" "${ENVVARS[@]}")
+fi
+if [ -z $TRIALS ]; then
+    TRIALS=( 1 )
 fi
 
 PWD=$(pwd)
 
-for CASE_DIR in "${CASES[@]}"
-do
-    for WRF_DIR in "${WRFs[@]}"
-    do
-        for N in "${NODES[@]}"
-        do
-            cd $PWD
-            WRF_PATH=$(readlink -f $WRF_DIR)
-            if [ -z $WRF_PATH ] || [ ! -d $WRF_PATH ]; then
-                echo "Invalid WRF_PATH: $WRF_DIR"
-                exit 1
-            fi
-            CASE_PATH=$(readlink -f $CASE_DIR)
-            if [ -z $CASE_PATH ] || [ ! -d $WRF_PATH ]; then
-                echo "Invalid CASE_PATH: $CASE_PATH"
-                exit 1
-            fi
+for TRIAL_NUM in "${TRIALS[@]}"; do
+    for CASE_DIR in "${CASES[@]}"; do
+        for WRF_DIR in "${WRFs[@]}"; do
+            for N in "${NODES[@]}"; do
+                cd $PWD
+                WRF_PATH=$(readlink -f $WRF_DIR)
+                if [ -z $WRF_PATH ] || [ ! -d $WRF_PATH ]; then
+                    echo "Invalid WRF_PATH: $WRF_DIR"
+                    exit 1
+                fi
+                CASE_PATH=$(readlink -f $CASE_DIR)
+                if [ -z $CASE_PATH ] || [ ! -d $WRF_PATH ]; then
+                    echo "Invalid CASE_PATH: $CASE_PATH"
+                    exit 1
+                fi
 
-            JOB_NAME=$(basename $CASE_DIR)-$(basename $WRF_DIR)-T$TRIAL_NUM-N$(printf "%03d" $N)
-            mkdir -p $RUN_DIR/$JOB_NAME
-            cd $RUN_DIR/$JOB_NAME
+                JOB_NAME=$(basename $CASE_DIR)-$(basename $WRF_DIR)-T$TRIAL_NUM-N$(printf "%03d" $N)
+                mkdir -p $RUN_DIR/$JOB_NAME
+                cd $RUN_DIR/$JOB_NAME
 
-            ln -sf $WRF_PATH/run/* .
-            ln -sf $CASE_PATH/namelist.input .  # must be second to overwrite default namelist.input
-            ln -sf $CASE_PATH/wrfbdy* .
-            ln -sf $CASE_PATH/wrfinput* .
-            ln -sf $CASE_PATH/wrfrst* .
+                ln -sf $WRF_PATH/run/* .
+                ln -sf $CASE_PATH/namelist.input .  # must be second to overwrite default namelist.input
+                ln -sf $CASE_PATH/wrfbdy* .
+                ln -sf $CASE_PATH/wrfinput* .
+                ln -sf $CASE_PATH/wrfrst* .
 
-            envsubst '${JOB_NAME},${N},${WALL_TIME},${ENV_STR}' > $JOB_NAME.pbs << EOF
+                envsubst '${JOB_NAME},${N},${WALL_TIME},${ENV_STR}' > $JOB_NAME.pbs << EOF
 #!/bin/bash
 #PBS -N ${JOB_NAME}
 #PBS -A SCSG0002
@@ -112,7 +123,8 @@ ${ENV_STR}
 
 ./mpirun_wrf $((${N} * 36))
 EOF
-            qsub $JOB_NAME.pbs
+                qsub $JOB_NAME.pbs
+            done
         done
     done
 done
